/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArrayGrid {
        "itemsArray": string[];
    }
}
declare global {
    interface HTMLArrayGridElement extends Components.ArrayGrid, HTMLStencilElement {
    }
    var HTMLArrayGridElement: {
        prototype: HTMLArrayGridElement;
        new (): HTMLArrayGridElement;
    };
    interface HTMLElementTagNameMap {
        "array-grid": HTMLArrayGridElement;
    }
}
declare namespace LocalJSX {
    interface ArrayGrid {
        "itemsArray"?: string[];
    }
    interface IntrinsicElements {
        "array-grid": ArrayGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "array-grid": LocalJSX.ArrayGrid & JSXBase.HTMLAttributes<HTMLArrayGridElement>;
        }
    }
}
